### ISSUE TITLE
data-textual does not build with GHC 8.8.1

### ISSUE THREAD

**Issue by vdukhovni** [mvv/data-textual#2]
```
...
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:312:35: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:346:35: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:657:34: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:733:34: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:931:36: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:967:36: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:1290:38: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:1369:38: error:
    • Could not deduce (MonadFail μ) arising from a use of ‘fail’
...
```
