### PR TITLE
Supports GHC 8.8

### LINKED ISSUE #2: data-textual does not build with GHC 8.8.1
```
...
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:312:35: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:346:35: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:657:34: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:733:34: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:931:36: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:967:36: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:1290:38: error:
data-textual-0.3.0.2/src/Data/Textual/Integral.hs:1369:38: error:
    • Could not deduce (MonadFail μ) arising from a use of ‘fail’
...
```

### PR DESCRIPTION
**Pull request by kakkun61**
`fail` is removed from `Monad` since base of GHC 8.8.

I have tested with GHC 8.4, 8.6, 8.8.

fixes #2

### CODE REVIEW

**Comment by kakkun61** [comment]
Sorry, I have just build it to test.

I'm fixing.

**Comment by kakkun61** [comment]
Are GHC 7.* supported yet? If yes, I will fix.

**Comment by kakkun61** [comment]
I found this to cause network-ip test failure. Please wait to review.

**Comment by mvv** [comment]
As with `data-serializer`, I've pushed a fix that does not require `MonadFail` in signatures. But I still want warning fixes from this PR. Please make a separate PR if you have the time. Thanks.
